Repository flucoma/flucoma-max, pull requests merged in 2021-11, with the labels that each got.

#61 Add return to load() when missing arguments
  source/include/FluidMaxWrapper.hpp
Labels: bug

#69 reconfigure fluid.plotter interface
  jsui/fluid.plotter.js
Labels: enhancement

#76 Copy misc folder on install target
  CMakeLists.txt
Labels: bug

#75 Add relative path file writing for data objects
  source/include/FluidMaxWrapper.hpp
Labels: enhancement

#29 ci/automatic building
  .github/workflows/nightly.yaml
Labels: enhancement

#82 Transients Help File
  help/fluid.transients~.maxhelp
Labels: documentation

#83 Sines Help File
  help/fluid.demosound.maxpat
  help/fluid.sines~.maxhelp
Labels: documentation

#79 KDTree Help File
  help/fluid.kdtree~.maxhelp
Labels: documentation
