Repository flucoma/flucoma-max, pull requests merged in 2022-06, with the labels that each got.

#228 [Docs] MLPRegressor Translation
  help/fluid.mlpregressor~.maxhelp
Labels: documentation

#250 [Enhance] Manual Documentation for CCE Objects
  CMakeLists.txt
  local_docs/fluid.buf2list.maxref.xml
  local_docs/fluid.list2buf.maxref.xml
  local_docs/fluid.plotter.maxref.xml
  local_docs/fluid.waveform~.maxref.xml
Labels: documentation, enhancement

#297 Issue 224
  source/include/FluidMaxWrapper.hpp
Labels: bug
